version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
#      Dockerfile этого образа содержит volume
#    volumes:
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - TZ=Europe/Moscow
  server:
    build: ./server/
    image: shareit-server:v1.2.0
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SR_PORT=9090
      - SR_DEBUG_PORT=9091
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9091"
#      - TZ=Europe/Moscow

  gateway:
    build: ./gateway/
    image: shareit-gateway:v1.2.0
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - GT_PORT=8080
      - GT_DEBUG_PORT=8081
      - SR_HOST=server
      - SR_PORT=9090
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081"
#      - TZ=Europe/Moscow